# app-of-apps/child-app1.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: child-app1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:javalove93/argocd-examples.git
    targetRevision: HEAD
    path: app-of-apps/child-app1
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

