apiVersion: apps/v1
kind: Deployment
metadata:
  name: child-app1
spec:
  replicas: 5
  selector:
    matchLabels:
      app: child-app1
  template:
    metadata:
      labels:
        app: child-app1
    spec:
      containers:
      - name: child-app1-nginx
        image: nginx
        ports:
        - containerPort: 80
